let forestLevel=createForestLevel(0),renderedBiome='meadow',streamForest=null,streamX=Infinity,streamZ=Infinity,streamRange=0,forestSoundAt=0,meadowGeometryLoaded=true,forestExitMesh=null;
const forestLogMeshes=new Map();
function inForest(){return player.biome==='forest'&&!isMenuScene();}
function forestDrawRange(){return inForest()?(settings.quality==='low'?105:155):(settings.quality==='low'?140:210);}
function clearForestStream(){streamForest=null;streamX=streamZ=Infinity;forestBuiltSeed=null;for(const mesh of forestLogMeshes.values())disposeFieldMesh(mesh);forestLogMeshes.clear();}
function unloadMeadowGeometry(){if(!meadowGeometryLoaded)return;for(const span of corridorSpans)disposeFieldMesh(span.mesh);for(const tower of corridorTowers)disposeFieldMesh(tower.shoes);disposeFieldMesh(corridorMesh);corridorSpans=[];corridorTowers=[];corridorColliders=[];corridorMesh=null;for(const t of otherTurbines){for(const m of t.meshes||[])disposeFieldMesh(m);t.meshes=null;}meadowGeometryLoaded=false;}
function restoreMeadowGeometry(){if(meadowGeometryLoaded)return;buildPowerCorridor();for(const t of otherTurbines)t.meshes=[makeLegMesh(),makeLegMesh(),makeLegMesh()];meadowGeometryLoaded=true;}
function resetForestLevel(){forestLevel=createForestLevel(activeLayout.seed);renderedBiome='meadow';player.biome='meadow';player.teleportSeq=0;player.levelCooldown=0;clearForestStream();restoreMeadowGeometry();document.body.classList.remove('forestLevel');}
function refreshForestStream(){if(!inForest())return;const range=forestDrawRange();if(streamForest&&Math.hypot(player.x-streamX,player.z-streamZ)<20&&range===streamRange)return;streamX=player.x;streamZ=player.z;streamRange=range;streamForest=forestView(activeLayout.seed,player.x,player.z,range+35);forestBuiltSeed=null;uploadWoodland(streamForest,[player.x-range-35,player.z-range-35,(range+35)*2,(range+35)*2]);const keys=new Set(streamForest.chunks.map(c=>c.key));for(const [key,mesh] of forestLogMeshes)if(!keys.has(key)){disposeFieldMesh(mesh);forestLogMeshes.delete(key);}for(const c of streamForest.chunks)if(c.logs.length&&!forestLogMeshes.has(c.key)){const g=infraGeometry();for(const log of c.logs)fallenLogGeometry(log,g);forestLogMeshes.set(c.key,mesh3D(g));}}
function updateForestLevelClient(dt){if(isMenuScene())return;if(!net.active&&game.mode==='playing'){player.alive=true;player.connected=true;tickForestBoundary(player,activeLayout,forestLevel,dt);tickForestLevel(forestLevel,[player],dt);}const biome=biomeOf(player);document.body.classList.toggle('forestLevel',biome==='forest');if(biome!==renderedBiome){renderedBiome=biome;clearForestStream();watchingEye=null;game.fadeIn=.96;keys.clear();game.vx=game.vz=0;game.notice=biome==='forest'?'FOREST / SIGNAL LOST':'MEADOW / SIGNAL RESTORED';game.noticeTime=4;proximityVoice.node?.port.postMessage({type:'clear'});proximityVoice.latest.clear();if(biome==='meadow'){restoreMeadowGeometry();uploadWoodland();}}if(inForest()){const occupied=net.active&&net.snapshots.at(-1)?.players.some(p=>p.connected&&p.alive&&biomeOf(p)==='meadow');if(!occupied)unloadMeadowGeometry();else restoreMeadowGeometry();refreshForestStream();if(game.mode==='playing'){forestSoundAt-=dt;if(forestSoundAt<=0){forestSoundAt=4+Math.random()*7;if(Math.random()<.5){sound.tone(240,180,.7,.018,'sine');sound.tone(320,200,.3,.012,'sine');}else sound.noise(.10,.035,800);}}}}
function appendForestDetails(){for(const [key,mesh] of forestLogMeshes){const c=streamForest.chunks.find(c=>c.key===key);if(c&&Math.hypot(player.x-c.x,player.z-c.z)<forestDrawRange()+38)objectDraws.push({mesh,model:identity(),material:5,assetKind:10,castShadow:true});}if(Math.hypot(player.x,player.z)<80){if(!forestExitMesh){const g=infraGeometry();for(const x of [-3.4,3.4]){const y=terrainHeight(x,4);infraBox(x,y+1,4,.16,2,.16,[.22,.19,.14],g);infraBox(x,y+1.55,4.095,.18,.24,.025,[.88,.88,.77],g);}forestExitMesh=mesh3D(g);}objectDraws.push({mesh:forestExitMesh,model:identity(),castShadow:true});}}
