import {chromium as playwright} from 'playwright';import chromium from '@sparticuz/chromium';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import assert from 'node:assert/strict';
const browser=await playwright.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,args:[...chromium.args,'--no-sandbox']});
try{
const page=await browser.newPage({viewport:{width:1000,height:600},isMobile:true,hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{window.requestAnimationFrame=()=>0;});await page.goto(pathToFileURL(resolve('public/index.html')).href);await page.waitForFunction(()=>running&&importedTextureRevision>=8);
await page.evaluate(()=>{window.qaTime=1000;settings.quality='low';settings.shadows='off';settings.vhs=.14;resolutionScale=.75;resize();grassRings=[[.7,65,0,55,0]];resetWorld(true,0);setMode('playing');locked=true;game.fadeIn=0;world.cycle=false;world.turbineStopped=world.powerStopped=true;
const t=forestForLayout(activeLayout).trees.find(t=>t.radius>.38&&Math.hypot(t.x-activeLayout.forest.x,t.z-activeLayout.forest.z)<80);player.x=t.x;player.z=t.z+4;player.yaw=0;player.pitch=.035;frame(qaTime+=16);watchingEye={tree:t,x:t.x,z:t.z+t.radius+.05,y:terrainHeight(t.x,t.z)+1.9,age:0,noticed:0,width:.85,nx:0,nz:1};frame(qaTime+=16);});await page.waitForFunction(()=>importedTextureRevision>=9);await page.evaluate(()=>frame(qaTime+=16));await page.screenshot({path:resolve('test/results/13/watching-eye-photo.png'),timeout:60000});
await page.evaluate(()=>{resetWorld(true,0);setMode('playing');locked=true;game.fadeIn=0;world.cycle=false;world.turbineStopped=world.powerStopped=true;player.x=120;player.z=-20;player.yaw=0;player.pitch=-.09;equippedTool='none';resetEquipmentMotion();equipmentMotion.shown='none';
appendNetworkObjects=()=>appendHazmat({id:'tablet-host',username:'HOST',x:120,z:-23,y:1.7,yaw:Math.PI,pitch:0,heldItem:'camera',tabletOpen:true},time);frame(qaTime+=16);});await page.screenshot({path:resolve('test/results/13/remote-host-tablet.png')});
assert.deepEqual(errors,[]);assert.equal(await page.evaluate(()=>gl.getError()),0);console.log({errors,remoteTablet:await page.evaluate(()=>objectDraws.filter(o=>o.tablet).length)});
}finally{await browser.close();}
